### ISSUE TITLE
other_visualization_scripts do not work

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#13]
Not all visualization scripts in the other_visualization_scripts folder work for me. The multiplot and query seem to, but not the ratio ones. See error messages below. Any idea what could cause this?

```
(base) C:\Users\nmpalmblad\Desktop\COVID-19\SCOPE\SCOPE-master>python other_visualization_scripts\visualize_multiplot.py
usage: visualize_multiplot.py [-h] -i input_folder -o output_filename
visualize_multiplot.py: error: the following arguments are required: -i, -o

(base) C:\Users\nmpalmblad\Desktop\COVID-19\SCOPE\SCOPE-master>python other_visualization_scripts\visualize_query.py
usage: visualize_query.py [-h] -i input -t input_type
visualize_query.py: error: the following arguments are required: -i, -t

(base) C:\Users\nmpalmblad\Desktop\COVID-19\SCOPE\SCOPE-master>python other_visualization_scripts\visualize_query_ratios.py
Traceback (most recent call last):
  File "other_visualization_scripts\visualize_query_ratios.py", line 218, in <module>
    main()
  File "other_visualization_scripts\visualize_query_ratios.py", line 209, in main
    table_1 = import_table(file_1) # , term ?
  File "other_visualization_scripts\visualize_query_ratios.py", line 25, in import_table
    f = open(file, 'r')
TypeError: expected str, bytes or os.PathLike object, not NoneType

(base) C:\Users\nmpalmblad\Desktop\COVID-19\SCOPE\SCOPE-master>python other_visualization_scripts\visualize_ratios.py
Traceback (most recent call last):
  File "other_visualization_scripts\visualize_ratios.py", line 630, in <module>
    main()
  File "other_visualization_scripts\visualize_ratios.py", line 616, in main
    term_1 = file_1.split('\\')[1].split('_')[0]
AttributeError: 'NoneType' object has no attribute 'split'

(base) C:\Users\nmpalmblad\Desktop\COVID-19\SCOPE\SCOPE-master>
```

**Comment by ReinV** [comment]
These scripts are old and I have a working ratio plot script that I will upload soon.
