### ISSUE TITLE
'DataFrame' object has no attribute 'Publication'

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#14]
I checked out the latest version today, and get (once I made a "2010-2019_ChEBI_IDs.tsv" file in "searches_by_year") the following error message. Do I need a complete set of decadal files in "searches_by_year"?

```
(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>python make_table.py -i results -t folder
getting searches by year ...
Traceback (most recent call last):
  File "make_table.py", line 141, in <module>
    main()
  File "make_table.py", line 112, in main
    chebi_to_npubs, N = get_statistics(df_sby)
  File "make_table.py", line 24, in get_statistics
    N = len(set(df.Publication))
  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\core\generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'Publication'

(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>
```

**Comment by magnuspalmblad** [comment]
OK, so with your "2010-2019_ChEBI_IDs.tsv" file in the "searches_by_year" folder I got a step further. I suppose we should place the "ChEBI2Class.tsv" file somewhere too!

```
(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>python make_table.py -i results -t folder
getting searches by year ...
results\COVID-19_ChEBI_IDs.tsv
making table for COVID-19
Traceback (most recent call last):
  File "make_table.py", line 141, in <module>
    main()
  File "make_table.py", line 132, in main
    data = import_properties()
  File "make_table.py", line 54, in import_properties
    df = pd.read_csv(file, sep='\t', header=None, names=['ChEBI', 'Info'], index_col='ChEBI')
  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File files/ChEBI2Class.tsv does not exist: 'files/ChEBI2Class.tsv'

(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>
```

**Comment by ReinV** [comment]
Oh right, for some reason on my pc I got errors with the “files/ChEBI2Superterms.tsv” file, so I renamed the file name to “ChEBI2Class.tsv”. Could you try that as well for now?

Van: Magnus Palmblad<mailto:notifications@github.com>
Verzonden: vrijdag 31 juli 2020 19:23
Aan: ReinV/SCOPE<mailto:SCOPE@noreply.github.com>
CC: Subscribed<mailto:subscribed@noreply.github.com>
Onderwerp: Re: [ReinV/SCOPE] 'DataFrame' object has no attribute 'Publication' (#14)


OK, so with your "2010-2019_ChEBI_IDs.tsv" file in the "searches_by_year" folder I got a step further. I suppose we should place the "ChEBI2Class.tsv" file somewhere too!

(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>python make_table.py -i results -t folder

getting searches by year ...

results\COVID-19_ChEBI_IDs.tsv

making table for COVID-19

Traceback (most recent call last):

  File "make_table.py", line 141, in <module>

    main()

  File "make_table.py", line 132, in main

    data = import_properties()

  File "make_table.py", line 54, in import_properties

    df = pd.read_csv(file, sep='\t', header=None, names=['ChEBI', 'Info'], index_col='ChEBI')

  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f

    return _read(filepath_or_buffer, kwds)

  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 448, in _read

    parser = TextFileReader(fp_or_buf, **kwds)

  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 880, in __init__

    self._make_engine(self.engine)

  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine

    self._engine = CParserWrapper(self.f, **self.options)

  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__

    self._reader = parsers.TextReader(src, **kwds)

  File "pandas\_libs\parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__

  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source

FileNotFoundError: [Errno 2] File files/ChEBI2Class.tsv does not exist: 'files/ChEBI2Class.tsv'



(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>

**Comment by magnuspalmblad** [comment]
Yes, this gets past this error.

**Comment by magnuspalmblad** [comment]
Hi Reinier,

Yes, I can confirmed this works now! I got all the way to the plot. The counts do not change with TFIDF.

I closed this issue on GitHub. Are there any other open issues that should be closed?

Will try the ratioplot next.


Cheers,

Magnus

________________________________

**Comment by ReinV** [comment]
Hi Magnus,

Thank you! Good point about the tables folder. I think issues #10 #11 #12 and #13 can be closed.

Greetings,

Reinier

Van: Magnus Palmblad<mailto:notifications@github.com>
Verzonden: zaterdag 1 augustus 2020 12:48
Aan: ReinV/SCOPE<mailto:SCOPE@noreply.github.com>
CC: ReinV<mailto:Rein_v@live.nl>; Comment<mailto:comment@noreply.github.com>
Onderwerp: Re: [ReinV/SCOPE] 'DataFrame' object has no attribute 'Publication' (#14)

Hi Reinier,

Yes, I can confirmed this works now! I got all the way to the plot. The counts do not change with TFIDF.

I closed this issue on GitHub. Are there any other open issues that should be closed?

Will try the ratioplot next.


Cheers,

Magnus

________________________________
