### ISSUE TITLE
No 'tables' folder in distribution

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#15]
The user needs to create the 'tables' folder, make_table.py does not do it automatically. Perhaps an empty folder can be included in the distribution?

```
making table for COVID-19
Traceback (most recent call last):
  File "make_table.py", line 141, in <module>
    main()
  File "make_table.py", line 138, in main
    write_to_file(table, term)
  File "make_table.py", line 87, in write_to_file
    table.to_csv(path+'_table.tsv', sep='\t')
  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\core\generic.py", line 3204, in to_csv
    formatter.save()
  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\formats\csvs.py", line 188, in save
    compression=dict(self.compression_args, method=self.compression),
  File "C:\Users\Magnus Palmblad\anaconda3\lib\site-packages\pandas\io\common.py", line 428, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'tables/COVID-19_table.tsv'
```

**Comment by ReinV** [comment]
A tables folder with HILIC and APCI tables is now included in the distribution.
