### ISSUE TITLE
Bugs in search_query.py?

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#27]
Even when specifying input queries, I get an error after retrieving "6000/5171" publications (which itself looks like a mistake).

This is what I get:

```
(base) C:\Users\nmpalmblad\Downloads\SCOPE-master>python search_query.py -i queries/input_queries.txt
searching with: (Metabolomics OR metabonomics) AND (METHODS:"Nuclear Magnetic Resonance" OR METHODS:NMR OR METHODS:"NMR spectrometry" OR METHODS:"nuclear magnetic resonance spectrometry" OR METHODS:"NMR spectroscopy" OR METHODS:"nuclear magnetic resonance (NMR) spectroscopy")
searching publications...
1000/5171 publications retrieved
2000/5171 publications retrieved
3000/5171 publications retrieved
4000/5171 publications retrieved
5000/5171 publications retrieved
6000/5171 publications retrieved
Traceback (most recent call last):
  File "search_query.py", line 215, in <module>
    main()
  File "search_query.py", line 210, in main
    chebi_dict = search_publications(query, pageSize)
  File "search_query.py", line 86, in search_publications
    nextcursormark = query_data['nextCursorMark']
KeyError: 'nextCursorMark'
```

**Comment by ReinV** [comment]
EuropePMC changed the nextCursorMark logic. Should now be fixed.
